markdown: rdiscount
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

host: nomospace.github.com

custom:
    category:
        node: node
        javascript: javascript
        css: css
    categories:
      - name: javascript
        title: javascript

      - name: node
        title: node

      - name: css
        title: css

meta:
    authors:
      - name: nomospace
        email: jinlu_hz@163.com
        gravatar: d6e8639fcaea0c7c0fab106033f05de0

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=80
